import os
import json
import time
import trimesh
import numpy as np
from pathlib import Path

from app.pipeline.mesh import build_mesh
from app.pipeline.profiles import FAST_QUALITY_V1
from app.pipeline.georef import load_georef

work_dir = Path("data/95f51b12-b771-47bf-9201-c3700f9475a7/work")
dense_dir = work_dir / "dense_full_ref2"
fused_ply = dense_dir / "fused.ply"

# Load points
pc = trimesh.load(str(fused_ply))
points = np.array(pc.vertices)
colors = np.array(pc.colors) if pc.colors is not None else np.zeros_like(points)

geo = json.loads((work_dir / "georef_data.json").read_text())
# We need sfm data. But sfm_data is usually generated by sfm_backend.
# If I just pass mock sfm with all cameras at [0,0,0], open3d might just point normals towards origin.
# Or better, I can just load sfm data from sparse_txt.
import sys
sys.path.append(str(Path(".").resolve()))
from app.pipeline.sfm_backend import read_cameras_text, read_images_text
cams = read_cameras_text(work_dir / "sparse/cameras.txt")
imgs = read_images_text(work_dir / "sparse/images.txt")
sfm = {"poses": {}}
for i, img in imgs.items():
    R = img.qvec2rotmat()
    t = img.tvec.reshape(3, 1)
    pose = np.hstack([R, t])
    sfm["poses"][img.name] = pose

t0 = time.monotonic()
mesh_obj, report = build_mesh(
    points=points,
    colors=colors,
    geo=geo,
    sfm=sfm,
    k=None,
    directory=work_dir / "images",
    out_dir=dense_dir, # dump mesh here
    options={
        **FAST_QUALITY_V1["mesh_settings"],
        "max_points": 500000,
        "texture_mesh": False # skip texture for now
    }
)
runtime = time.monotonic() - t0

print(f"Runtime: {runtime:.1f}s")
print("Metrics:")
for k, v in report.items():
    print(f"  {k}: {v}")
