"""Add readiness columns

Revision ID: 586987a4bb10
Revises: 13027d2e6cf9
Create Date: 2026-09-15 01:56:07.059894

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "586987a4bb10"
down_revision: Union[str, Sequence[str], None] = "13027d2e6cf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("readiness_status", sa.String(length=24), nullable=False))
        batch_op.add_column(sa.Column("readiness_score", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("readiness_report_path", sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("readiness_report_path")
        batch_op.drop_column("readiness_score")
        batch_op.drop_column("readiness_status")

    # ### end Alembic commands ###
